<?php

declare(strict_types=1);

use AliYavari\IranPayment\Contracts\Payment as PaymentInterface;
use AliYavari\IranPayment\Drivers\FakeDriver;
use AliYavari\IranPayment\Dtos\PaymentRedirectDto;
use AliYavari\IranPayment\Exceptions\DriverBehaviorNotDefinedException;
use AliYavari\IranPayment\Exceptions\InvalidCallbackDataException;
use AliYavari\IranPayment\Facades\Payment;
use Illuminate\Support\Facades\Config;

dataset('gateway_connections', [
    'behpardakht' => ['behpardakht', SoapFault::class],
]);

it('returns a fake instance for the default gateway', function (): void {
    Config::set('iran-payment.default', 'default_gateway');

    Payment::fake();

    $payment = Payment::gateway('default_gateway');

    expect($payment)
        ->toBeInstanceOf(FakeDriver::class)
        ->getGateway()->toBe('default_gateway');
});

it('returns a fake instance for a specified gateway', function (): void {
    Payment::fake('specific_gateway');

    $payment = Payment::gateway('specific_gateway');

    expect($payment)
        ->toBeInstanceOf(FakeDriver::class)
        ->getGateway()->toBe('specific_gateway');
});

it('throws an exception when the create behavior is not defined', function (): void {
    fakeTestGateway();

    testGateway()->create(10);
})->throws(DriverBehaviorNotDefinedException::class, 'No behavior has been defined for the "create" method on the fake driver "test_gateway".');

it('fakes a successful create API response using default data', function (): void {
    fakeTestGateway()->successfulCreate();

    $payment = testGateway()->create(10);

    expect($payment)
        ->successful()->toBeTrue()
        ->error()->toBeNull()
        ->getRawResponse()->toBe('Creation raw response')
        ->getTransactionId()->toHaveLength(15) // Unique number generated by the package.
        ->getGatewayPayload()->toBe(['payload' => 'test value'])
        ->getRedirectData()->scoped(
            fn ($redirectData) => $redirectData
                ->url->toBe('https://gateway.test')
                ->method->toBe('POST')
                ->payload->toBe(['status' => 'successful'])
                ->headers->toBe(['X-IranPayment-Fake' => 'true'])
        );
});

it('fakes a successful create API response using user-defined redirect data', function (): void {
    $customRedirectData = new PaymentRedirectDto(
        url: 'http://test.org',
        method: 'PUT',
        payload: ['key' => 'payload value'],
        headers: ['x-test-header' => 'header value'],
    );

    fakeTestGateway()->successfulCreate(redirectData: $customRedirectData);

    $payment = testGateway()->create(10);

    expect($payment)
        ->successful()->toBeTrue()
        ->error()->toBeNull()
        ->getRedirectData()->toBe($customRedirectData);
});

it('fakes a failed create API response', function (): void {
    fakeTestGateway()->failedCreate();

    $payment = testGateway()->create(10);

    expect($payment)
        ->failed()->toBeTrue()
        ->error()->toBe('کد 0- Creation failed')
        ->getRawResponse()->toBe('Creation raw response');
});

it('throws a connection exception on the create API', function (string $gateway, string $connectionType): void {
    Payment::fake($gateway)->failedConnectionCreate();

    expect(fn () => Payment::gateway($gateway)->create(10))
        ->toThrow(
            $connectionType,
            'Creation connection failed'
        );
})->with('gateway_connections');

it('creates payment instance with no callback data', function (): void {
    fakeTestGateway();

    $payment = testGateway()->noCallback('123');

    expect($payment)
        ->getTransactionId()->toBe('123');
});

it('creates payment instance with callback data', function (): void {
    fakeTestGateway();

    $payment = testGateway()->fromCallback(['key' => '123']);

    expect($payment)
        ->toBeInstanceOf(PaymentInterface::class);
});

it('throws invalid callback exception', function (): void {
    fakeTestGateway()->invalidCallback();

    testGateway(runVerification: true);
})->throws(InvalidCallbackDataException::class, 'Invalid callback data');

it('throws an exception when the verify behavior is not defined', function (): void {
    fakeTestGateway();

    testGateway(runVerification: true);
})->throws(DriverBehaviorNotDefinedException::class, 'No behavior has been defined for the "verify" method on the fake driver "test_gateway".');

it('fakes a successful verify API response', function (): void {
    fakeTestGateway()->successfulVerify();

    $payment = testGateway(runVerification: true);

    expect($payment)
        ->successful()->toBeTrue()
        ->error()->toBeNull()
        ->getRawResponse()->toBe('Verification raw response')
        ->getCardNumber()->toBe('1234-****-****-1234')
        ->getRefNumber()->toBe('123456789');
});

it('fakes a failed verify API response', function (): void {
    fakeTestGateway()->failedVerify();

    $payment = testGateway(runVerification: true);

    expect($payment)
        ->failed()->toBeTrue()
        ->error()->toBe('کد 0- Verification failed')
        ->getRawResponse()->toBe('Verification raw response');
});

it('throws a connection exception on the verify API', function (string $gateway, string $connectionType): void {
    Payment::fake($gateway)->failedConnectionVerify();

    $payment = Payment::gateway($gateway)->fromCallback([]);

    expect(fn () => $payment->verify([]))
        ->toThrow(
            $connectionType,
            'Verification connection failed'
        );
})->with('gateway_connections');

it('throws an exception when the settle behavior is not defined', function (): void {
    fakeTestGateway()->successfulVerify();

    testGateway(runVerification: true)->settle();
})->throws(DriverBehaviorNotDefinedException::class, 'No behavior has been defined for the "settle" method on the fake driver "test_gateway".');

it('fakes a successful settle API response', function (): void {
    fakeTestGateway()->successfulVerify()->successfulSettle();

    $payment = testGateway(runVerification: true)->settle();

    expect($payment)
        ->successful()->toBeTrue()
        ->error()->toBeNull()
        ->getRawResponse()->toBe('Settlement raw response');
});

it('fakes a failed settle API response', function (): void {
    fakeTestGateway()->successfulVerify()->failedSettle();

    $payment = testGateway(runVerification: true)->settle();

    expect($payment)
        ->failed()->toBeTrue()
        ->error()->toBe('کد 0- Settlement failed')
        ->getRawResponse()->toBe('Settlement raw response');
});

it('throws a connection exception on the settle API', function (string $gateway, string $connectionType): void {
    Payment::fake($gateway)->successfulVerify()->failedConnectionSettle();

    $payment = Payment::gateway($gateway)->fromCallback([])->verify([]);

    expect(fn () => $payment->settle())
        ->toThrow(
            $connectionType,
            'Settlement connection failed'
        );
})->with('gateway_connections');

it('throws an exception when the reverse behavior is not defined', function (): void {
    fakeTestGateway()->successfulVerify();

    testGateway(runVerification: true)->reverse();
})->throws(DriverBehaviorNotDefinedException::class, 'No behavior has been defined for the "reverse" method on the fake driver "test_gateway".');

it('fakes a successful reverse API response', function (): void {
    fakeTestGateway()->successfulVerify()->successfulReverse();

    $payment = testGateway(runVerification: true)->reverse();

    expect($payment)
        ->successful()->toBeTrue()
        ->error()->toBeNull()
        ->getRawResponse()->toBe('Reversal raw response');
});

it('fakes a failed reverse API response', function (): void {
    fakeTestGateway()->successfulVerify()->failedReverse();

    $payment = testGateway(runVerification: true)->reverse();

    expect($payment)
        ->failed()->toBeTrue()
        ->error()->toBe('کد 0- Reversal failed')
        ->getRawResponse()->toBe('Reversal raw response');
});

it('throws a connection exception on the reverse API', function (string $gateway, string $connectionType): void {
    Payment::fake($gateway)->successfulVerify()->failedConnectionReverse();

    $payment = Payment::gateway($gateway)->fromCallback([])->verify([]);

    expect(fn () => $payment->reverse())
        ->toThrow(
            $connectionType,
            'Reversal connection failed'
        );
})->with('gateway_connections');

// ------------
// Helpers
// ------------

function fakeTestGateway(): FakeDriver
{
    return Payment::fake('test_gateway');
}

function testGateway(bool $runVerification = false): PaymentInterface
{
    $payment = Payment::gateway('test_gateway');

    if ($runVerification) {
        $payment->fromCallback([])->verify([]);
    }

    return $payment;
}
